apiVersion: app.example.com/v1
kind: AppService
metadata:
  labels:
    app.kubernetes.io/name: appservice
    app.kubernetes.io/instance: appservice-sample
    app.kubernetes.io/part-of: opdemo
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: opdemo
  name: appservice-sample
spec:
  # TODO(user): Add fields here
  size: 2
  image: nginx:1.7.9
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002